#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROJECTS = ROOT / "projects"
TEMPLATES = ROOT / "templates"


def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "-", text)
    text = text.strip("-")
    return text[:80] or "entry"


def render_template(template_name: str, values: dict[str, str]) -> str:
    path = TEMPLATES / template_name
    text = path.read_text()
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", value)
    return text


def new_entry(args: argparse.Namespace) -> None:
    created = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    slug = slugify(args.title)
    kind = args.kind
    project = args.project
    entry_dir = PROJECTS / project / kind / f"{stamp}-{slug}"
    entry_dir.mkdir(parents=True, exist_ok=False)

    template = {
        "experiments": "experiment.md",
        "decisions": "decision.md",
        "literature": "literature.md",
    }.get(kind, "entry.md")
    values = {
        "title": args.title,
        "project": project,
        "kind": kind,
        "created_at": created,
    }
    (entry_dir / "ENTRY.md").write_text(render_template(template, values))
    metadata = {
        "title": args.title,
        "project": project,
        "kind": kind,
        "created_at": created,
        "status": "draft",
        "links": [],
        "raw_data_read_only": True,
    }
    (entry_dir / "metadata.json").write_text(json.dumps(metadata, indent=2, ensure_ascii=False) + "\n")
    (entry_dir / "artifacts").mkdir()
    print(entry_dir)


def load_metadata(path: Path) -> dict[str, str]:
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


def rebuild_index(_: argparse.Namespace) -> None:
    project_lines = []
    entry_rows = []
    for project_dir in sorted(PROJECTS.iterdir()):
        if not project_dir.is_dir():
            continue
        project_md = project_dir / "PROJECT.md"
        if project_md.exists():
            project_lines.append(f"- [{project_dir.name}]({project_md.relative_to(ROOT)})")
        for metadata_path in sorted(project_dir.glob("*/*/metadata.json")):
            meta = load_metadata(metadata_path)
            entry_md = metadata_path.parent / "ENTRY.md"
            if not entry_md.exists():
                continue
            entry_rows.append(
                {
                    "created_at": meta.get("created_at", ""),
                    "project": meta.get("project", project_dir.name),
                    "kind": meta.get("kind", metadata_path.parent.parent.name),
                    "title": meta.get("title", metadata_path.parent.name),
                    "status": meta.get("status", ""),
                    "path": str(entry_md.relative_to(ROOT)),
                }
            )
    entry_rows.sort(key=lambda row: row["created_at"], reverse=True)
    lines = [
        "# Research Memory Index",
        "",
        "This file is regenerated by `research_memory/scripts/mem.py index`.",
        "",
        "## Projects",
        "",
        *(project_lines or ["No projects found."]),
        "",
        "## Entries",
        "",
        "| created_at | project | kind | status | title |",
        "|---|---|---|---|---|",
    ]
    for row in entry_rows:
        lines.append(
            f"| {row['created_at']} | {row['project']} | {row['kind']} | "
            f"{row['status']} | [{row['title']}]({row['path']}) |"
        )
    if not entry_rows:
        lines.append("| | | | | No entries yet. |")
    (ROOT / "INDEX.md").write_text("\n".join(lines) + "\n")
    (ROOT / "registry" / "entries.json").write_text(json.dumps(entry_rows, indent=2, ensure_ascii=False) + "\n")
    print(ROOT / "INDEX.md")


def log_note(args: argparse.Namespace) -> None:
    now = datetime.now()
    day = now.strftime("%Y-%m-%d")
    stamp = now.strftime("%H:%M:%S")
    inbox_dir = ROOT / "inbox"
    inbox_dir.mkdir(parents=True, exist_ok=True)
    path = inbox_dir / f"{day}.md"
    if not path.exists():
        path.write_text(f"# Inbox: {day}\n\n")
    with path.open("a") as f:
        f.write(f"## {stamp} {args.project}\n\n")
        f.write(args.text.strip() + "\n\n")
    print(path)


def main() -> None:
    parser = argparse.ArgumentParser(prog="mem.py")
    sub = parser.add_subparsers(dest="cmd", required=True)

    new_parser = sub.add_parser("new", help="create a new memory entry")
    new_parser.add_argument("--project", required=True)
    new_parser.add_argument(
        "--kind",
        required=True,
        choices=["literature", "ideas", "experiments", "decisions", "meetings", "runs", "notes"],
    )
    new_parser.add_argument("--title", required=True)
    new_parser.set_defaults(func=new_entry)

    index_parser = sub.add_parser("index", help="rebuild global index")
    index_parser.set_defaults(func=rebuild_index)

    log_parser = sub.add_parser("log", help="append a lightweight daily inbox note")
    log_parser.add_argument("--project", required=True)
    log_parser.add_argument("--text", required=True)
    log_parser.set_defaults(func=log_note)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
